package main

func main() {
	/*
		try...catch...finally

		defer：延迟
		panic:恐慌
			让当前的一条协程进入恐慌，中断程序的执行。
		recover:恢复
			让程序恢复，必须在defer函数中执行。

		go语言没有异常机制，它不能抛出异常，而是使用了panic和recover机制。--->把它作为最后的手段来使用。
	*/
}
